language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
  - 'node'
  - '6'
cache:
  directories:
    - $HOME/.cache/bower
    - node_modules
install:
  - npm install yarn -g
  - npm install -g polymer-cli@next
  - yarn install --flat
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run lint
script:
  - node --max-old-space-size=3072 ./node_modules/.bin/polymer build
